# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'technica' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for technica
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'technica-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'technicaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'technica-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for technica-tvOS

end
